/* jshint node: true */
/* jshint esnext: true */
'use strict';
var config = {
    "app_port": 8077,
    "login_salt_length" : 10,
    "random_password_length" : 8,
     "random_password_allowed_characters" : "abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+~`|}{[]\:;?><,./-=",
    "random_capital_allowed_characters" : "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "random_small_allowed_characters" : "abcdefghijklnopqrstuvwxyz",
    "random_number_allowed_characters" : "0123456789",
    "random_special_allowed_characters" : "!@#$%^&*()_+~`|}{[]\:;?><,./-=",
    "checkIntegerValue" : /^\d+$/,
    "emailPattern" : /[\w-]+@([\w-]+\.)+[\w-]+/,
    "urlPattern"   : "(http|https)://[\w-]+(\.[\w-]+)+([\w.,@?^=%&amp;:/~+#-]*[\w@?^=%&amp;/~+#-])?",
    "mscode": "sbiclaims",
    "default_error_code": 1,
    "default_error_message": "Sorry, invalid request",
    "default_success_code": 0,
    "default_success_message": "Successfully processed the request",
    "unauthorized_access_message": "You are not authorized to access",
    "server_error_http_code": 403,
    "redis_down_message": "Internal Error",
    "doc_path": "/usr/share/nginx/html/uploads",
    "checkIntegerValue": /^\d+$/,
    "platformDb": "SBI_CLIMS_DEV",
    "alphaSpaceReg": /^[A-Za-z\s]+$/,
    "alphaSpaceDotReg": /^[A-Za-z\s.]+$/,
    "englishCharReg": /^[\x20-\x7E]+$/,
    "emailPatternReg": /[\w-]+@([\w-]+\.)+[\w-]+/,
    "bloodGroupReg": /^(A|B|AB|O)[+-]$/,
    "aplhaNumSpaceDotDashReg": /^[a-z\d\-_.\s]+$/i,
    "aplhaNumSpaceReg": /^[a-z\d\s]+$/i,
    "defaultInternalErrorCode": 500,
    "defaultInternalErrorMessage": 'Internal Error !!',
    "iteratorLimit": 50,
    "randomPasswordLength": 8,     
    "sql_error_message" : {
        "ECONNREFUSED" : "Unable to connect to the database",
        1005 : "Error in creating the table",
        1006 : "Error in creating the database",
        1007 : "Cannot create new database with the existing name",
        1008 : "Cannot drop the database as it does not exists",
        1009 : "Cannot drop the database",
        1010 : "Error encountered dropping the database",
        1011 : "Error encountered on delete operation",
        1020 : "Record has changed since last read in table",
        1021 : "Cannot write database disk space is full",
        1022 : "Cannot write duplicate key in the table",
        1036 : "Cannot write table is in read only mode",
        1037 : "Database ran out of memory",
        1040 : "Too many connections to database",
        1041 : "Out of memory error for database",
        1042 : "Cannot get hostname for connecting database",
        1044 : "Access denied for the database",
        1045 : "Access denied for connecting to the database",
        1046 : "Database is not selected",
        1048 : "Null value passed for the column",
        1049 : "Unknown database",
        1050 : "Table already exists",
        1051 : "Unknown table",
        1053 : "Database is shutting down",
        1054 : "Unknown column",
        1058 : "Column count doesn't match value count",
        1060 : "Duplicate column name",
        1061 : "Duplicate key name",
        1062 : "Duplicate data passed for entry",
        1063 : "Incorrect column specifier",
        1065 : "Empty query passed",
        1102 : "Incorrect database name",
        1103 : "Incorrect table name",
        1110 : "Column specified twice",
        1114 : "Table is full",
        1136 : "Number of columns and values does not match",
        1146 : "Table does not exists",
        1151 : "Too many delayed threads in use",
        1154 : "Got a read error from the connection pipe",
        1159 : "Got timeout reading communication packets",
        1160 : "Got an error writing communication packets",
        1161 : "Got timeout writing communication packets",
        1166 : "Incorrect column name",
        1169 : "Cannot write duplicate data for unique column",
        1176 : "Key does not exist in the table",
        1177 : "Cannot open table",
        1179 : "You are not allowed to execute this operation in a transaction",
        1180 : "Got error during COMMIT",
        1181 : "Got error during ROLLBACK",
        1184 : "Aborted database connection",
        1192 : "Cannot perform the operation due to active locked tables or an active transaction",
        1203 : "Database user already has more than maximum allowed active connections",
        1205 : "Transaction lock wait timeout exceeded",
        1206 : "The total number of locks exceeds the lock table size",
        1215 : "Cannot add foreign key constraint",
        1216 : "Cannot add or update a child row due to foreign key constraint failure",
        1217 : "Cannot delete or update a parent row due to foreign key constraint fails",
        1317 : "Query execution was interrupted",
        1343 : "Error encountered parsing query parameter",
        1637 : "Too many active concurrent transactions",
        1698 : "Access denied for the user to connect to the database"
    }   
};

module.exports = config;
